- locale/tr.yml
I added turkish language locale!
> Turkish Language Added

- composer.json
- js/admin/dist/extension.js
- js/admin/src/components/UploadPage.js
- locale/en.yml
- src/Adapters/OVH.php
- src/Helpers/Settings.php
- src/Providers/StorageServiceProvider.php
This pull request adds support for OVH's file storage service and is significantly cheaper than S3's storage.
This was a collaborative effort between @Webeindustry and I.
> Add OVH Support (w/ Webeindustry's Assistance)

- locale/es.yml
This file has not been tested. 
Added the Spanish (Castilian) translation yml file. It uses the respectful way of spanish (aka Usted) and might not be the best translation, but it is better than nothing!
> Added spanish translation.

- locale/it.yml
Added ovh-svfs and small lang update
> Updated it.yml

- src/Listeners/ProcessesImages.php
- src/Processors/ImageProcessor.php
> fix handling of svg and unsupported image types (fixes #68)

- locale/pl.yml
Added strings for hotlink protection and data logging. Replaced two strings with more appriopate version.
> Polish translation

- locale/kr.yml
This patch has been applied into my [forum site](https://forum.mathch.at).
Please check and merge it for next release.
Signed-off-by: Comocozy <woogyom@comocozy.com>
> locale: Support Korean translation

- src/Adapters/AwsS3.php
> added support for amazon s3 cdn #149

- src/Adapters/Local.php
https://github.com/flagrow/upload/issues/172
> delete the target location when assets or assets/files is a symbolic link

- resources/locale/de.yml
Old translations were very bad
> Small updates to German translations

- composer.json
- js/src/admin/components/UploadPage.js
- resources/locale/cn.yml
- resources/locale/en.yml
- resources/locale/zh.yml
- src/Adapters/Qiniu.php
- src/Helpers/Settings.php
- src/Providers/StorageServiceProvider.php
> Add qiniu storage

- extend.php
- src/Extenders/CreateStorageFolder.php
This fixes a notice with tmpname by creating the tmp dir inside the storage dir
> Fix a notice with tmpname

- js/src/admin/components/UploadPage.js
- resources/locale/en.yml
- src/Adapters/AwsS3.php
- src/Adapters/Flysystem.php
- src/Adapters/Manager.php
Picking up from where #238 appeared to stall.
Tested locally with `localstack`, and with Linode object storage
> S3 Compatible storage #164

- src/Downloader/DefaultDownloader.php
> Split local storage file retrieval

- src/Helpers/Util.php
Signed-off-by: Andreas Hofmann <git@andreas-hofmann.org>
> Helpers/Util.php: Fix getting mimeTypes setting.

- LICENSE
- README.md
- composer.json
- extend.php
- js/package-lock.json
- js/package.json
- js/src/admin/components/UploadPage.js
- js/src/admin/index.js
- js/src/common/models/File.js
- js/src/forum/addUploadButton.js
- js/src/forum/components/FileManagerButton.js
- js/src/forum/components/UploadButton.js
- js/src/forum/downloadButtonInteraction.js
- js/src/forum/handler/Uploader.js
- js/src/forum/index.js
- js/src/forum/states/FileListState.js
- migrations/2020_02_06_02_rename_flagrow_settings.php
- migrations/2020_02_06_07_alter_downloads_add_post_constraint.php
- src/Adapters/AwsS3.php
- src/Adapters/Local.php
- src/Adapters/Qiniu.php
- src/Commands/UploadHandler.php
- src/Downloader/DefaultDownloader.php
- src/Helpers/Util.php
- src/Providers/DownloadProvider.php
- src/Providers/UtilProvider.php
- src/Repositories/FileRepository.php
- src/Templates/AbstractTemplate.php
- src/Validators/UploadValidator.php
> Updated to beta.16

- js/src/forum/components/index.js
I have a use case to extend this component, but since it's not exported it's not easily extended.
Ensure the extension still builds as expected.
> Export UploadButton component

- composer.json
- extend.php
- src/Commands/UploadHandler.php
- src/Extend/SvgSanitizer.php
- src/Providers/SanitizerProvider.php
- src/Sanitizer/SvgAllowedAttrs.php
- src/Sanitizer/SvgAllowedTags.php
Should also address https://github.com/FriendsOfFlarum/upload/issues/68
> Clean and validate uploaded SVG files

- extend.php
> chore: disable cli cleanup command

- extend.php
- js/src/admin/components/UploadImageButton.ts
- js/src/admin/components/UploadPage.js
- src/Api/Controllers/WatermarkDeleteController.php
- src/Api/Controllers/WatermarkUploadController.php
- src/Extenders/AddForumAttributes.php
- src/Processors/ImageProcessor.php
> fix: upload watermark image does not display in settings

- js/src/forum/components/FileManagerModal.js
Another catch.
Before:
After:
**Confirmed**
> fix: release to upload translation key

- extend.php
- src/Downloader/DefaultDownloader.php
> [WIP] Remediate issues with Private Shares causing Error 500

- js/src/forum/components/UploadsUserPage.tsx
**Partially Fixes https://github.com/FriendsOfFlarum/upload/issues/393**
Redraw when deleting file in `UploadsUserPage`
**Screenshot**
**Confirmed**
> fix: redraw after deleting file

- .github/workflows/backend.yml
- composer.json
- extend.php
- resources/locale/en.yml
- src/Api/Controllers/InspectMimeController.php
- src/Mime/Mapping/APK.php
- src/Mime/Mapping/AbstractMimeMap.php
- src/Mime/MimeTypeDetector.php
- src/Providers/MimeMappingProvider.php
- src/Repositories/FileRepository.php
- Bumps the minimum PHP version to 8.1 (due to 3rd party library constraints)
> feat: detect apk mimetypes

- src/Formatter/TextPreview/FormatTextPreview.php
> fix: text preview assumes file is on local storage

- .gitignore
- extend.php
- js/src/admin/components/UploadPage.js
- resources/locale/en.yml
- src/Providers/SanitizerProvider.php
> fix: Animated SVGs allowed by default, introducing a potential security vulnerability

- js/src/common/states/FileListState.ts
https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension/2445
TBD
How can we resolve the TS error introduced here?
**Screenshot**
**Confirmed**
> fix: prevent shared files being duplicated
