FriendsOfFlarum/upload

- locale/fr.yml
- changed key in admin > labels > preferences, from mime_types_allowed to mime_types, to match structure of 0.4.3 en.yml. Translation was fine, so no change applied for it.
- added mime_types key in admin> help_texts with translation, to match structure of 0.4.3 en.yml
> Update to fr.yml

- src/Adapters/AwsS3.php
As best practice on AWS, you should use the static website hosting feature instead of making your bucket become public. With the static website hosting feature, you could also utilise its redirection feature to utilise CDN like AWS Cloudfront to serve public traffic to your S3 bucket. For more information, please read: https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
> Use S3 Static website hosting instead

- src/Adapters/AwsS3.php
I've not tested this locally yet.
This was introduced in #124 and most likely would negatively impact any HTTPS website using s3.
> Use https for s3 links

- src/Processors/ImageProcessor.php
An image uploaded with exif orientation metadata is now saved correctly.
Originally reported by a giffgaff member:
> {username} mentioned this again at https://community.giffgaff.com/d/33030918-unable-to-upload-portrait-photo-always-auto-rotated-to-landscape and gave me a link to a photo which always uploades as landscape, despite being clearly intended to be portrait.
> The original is downloadable from https://photos.app.goo.gl/Cvz4nsok9VzPDc1r7 -- if you download the photo from there you will see it still shows as portrait (in a windows 10 folder, it might not do everywhere) but uploads to the forum 'sideways'
> I opened the original in aftershot pro and looked at the metadata:
> As you see, that camera is saving the image with an exif "width" that's greater than its "height" as if …
> Correctly orientate an image with exif data

- composer.json
- src/Commands/UploadHandler.php
- src/Contracts/Processable.php
- src/Events/File/Event.php
- src/Extenders/AddImageProcessor.php
- src/Processors/ImageProcessor.php
- src/Repositories/FileRepository.php
Uses 'magic byte' detection of the mimetype, rather than using the supplied mime from the client
> Ensure mimeTypes are what they appear to be

- src/Adapters/AwsS3.php
Follows luceos request for a more readable solution in #184
> Fix url when using cdnUrl with S3. Null url was incorrectly used as path

- resources/locale/en.yml
- src/Commands/UploadHandler.php
I extracted three error message strings because i needed them to be translatable via Linguist. I guess this makes sense for everyone.
> Extract error message strings to be translatable

- js/src/admin/components/UploadPage.js
- resources/locale/en.yml
- src/Repositories/FileRepository.php
Fixes #224 
Fixes #221 
Related #9
I have pondered a few solutions for this issue and I don't think we can make a generic solution that works out of the box for everyone.
So this solution introduces a whitelist for files we won't attempt to rename.
I believe it also fixes a security issue where you could get the original client extension be used for files for which we couldn't guess the extension, which kind of defeats the whole purpose.
Now the extension defaults to `bin` if no other extension can be determined.
The client-provided file extension is only used if it's in the whitelist.
This solution should even cover the case of those who wanted to whitelist PHP files (we've had this request in the past). It's the responsibility of the forum owner to check the file extensions they …
> Add client file extension whitelist feature

- resources/locale/en.yml
- src/Contracts/Template.php
- src/Contracts/TextFormatterTemplate.php
- src/Extenders/AddPostDownloadTags.php
- src/File.php
- src/Helpers/Settings.php
- src/Providers/DownloadProvider.php
- src/Templates/AbstractTemplate.php
- src/Templates/AbstractTextFormatterTemplate.php
- src/Templates/FileTemplate.php
- src/Templates/ImagePreviewTemplate.php
- src/Templates/ImageTemplate.php
- src/Templates/JustUrlTemplate.php
Fixes #187
Our current implementation isn't really friendly with custom templates that don't rely on bbcode. You could register a fake bbcode that you're not actually using but it's not super pretty or obvious.
This PR introduces interfaces for custom templates, with a separate interface if you want Upload to register the bbcode.
The PR also adds a new "just-url" template which... just inserts the URL. That way the extension can be used with AutoImage, AutoVideo and probably other extensions out of the box without the need to write that super simple template.
Backward compatibility questions:
This was almost a backward-compatible change but unfortunately the use of the separate interface that `AbstractTemplate` doesn't implement means custom templates would lose their bbcode. We could …
> Interfaces for templates. Allow non-bbcode templates. Add URL template

- js/src/forum/addUploadButton.js
At the moment, the ext attempts to preview the content after the upload succeeds, but this creates an error if attempted on a new discussion.
By wrapping the `.preview()` code in a `typeof` check, we can ensure that the post is only previewed if supported.
> Fix console error when uploading to a new discussion OP

- js/src/forum/components/UploadButton.js
Sometimes, if a file has been uploaded, and the dialog is opened again and cancelled, the ext attempts to upload an empty set of files.
This fails, and shows an error (see video below).
This PR ensures that uploads are only attempted if at least 1 file is selected.
https://user-images.githubusercontent.com/7406822/104103952-fc86ca80-529c-11eb-8ca7-6e3b98962254.mp4
> Fix console error when cancelling upload dialog

- js/src/forum/components/UploadButton.js
- resources/less/forum/upload.less
At the moment, there's an input element inside the toolbar button. This input is rendered, and layered just below the button itself. The entire file selection process is handled by the input, so any clicks on the button which are just outside the input element are ignored.
This PR prevents the input being rendered entirely, substituting `opacity: 0` with `display: none`. Then, we add an `onclick` handler to the toolbar button which triggers the input dialog to open.
After this, everything continues as normal.
---
This also removes the need for focus styling hacks: currently the focus is given to the input element, meaning that we can't use `:focus-visible` to provide keyboard-only focus styles to the button, instead having to use `:focus-within`, which also shows these focus styles when …
> Remove invisible input hack in upload toolbar

- resources/less/forum/upload.less
This PR allows keyboard users to see what the upload button does (shows the upload text on focus).
Previously, the text was only shown on hover and, because there was no tooltip, there was no way to see the function of the button.
https://user-images.githubusercontent.com/7406822/104962650-c8b05100-59d0-11eb-8e9e-19b212c28ec8.mp4
> Afford keyboard navigators the same styling rights as mouse users

- extend.php
- js/package-lock.json
- js/src/admin/index.js
- js/src/common/mimeToIcon.js
- js/src/common/models/File.js
- js/src/forum/components/FileManagerModal.js
- js/src/forum/components/UploadButton.js
- js/src/forum/components/UploadsUserPage.js
- js/src/forum/components/UserFileList.js
- js/src/forum/index.js
- migrations/2021_03_13_000000_alter_upload_files_add_hidden_from_media_manager.php
- migrations/2021_03_13_set_created_at_to_default_as_current_timestamp.php
- resources/less/forum/download.less
- resources/less/forum/fileList.less
- resources/locale/en.yml
- src/Api/Controllers/HideUploadFromMediaManagerController.php
- src/Api/Controllers/ListUploadsController.php
- src/Api/Serializers/FileSerializer.php
- src/Extenders/AddCurrentUserAttributes.php
- src/Extenders/AddForumAttributes.php
- src/File.php
> Add options to hide uploads from Mediamanager

- js/src/forum/addUploadButton.js
- js/src/forum/components/PasteClipboard.js
Don't depend on a textarea. This will bring compatibility with core's upcoming editor drivers system. See https://github.com/flarum/core/issues/2566.
> Editor Driver Support

- src/Repositories/FileRepository.php
/**
* sometimes function tempnam() maybe show notice
* https://www.php.net/manual/zh/function.tempnam.php
*
* Please note that this function might throw a notice in PHP 7.1.0 and above.
* This was a bugfix: https://bugs.php.net/bug.php?id=69489
* PHP Notice:tempnam(): file created in the system's temporary directory
*
* That Notice will lead to
* Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException:
* Output has been emitted previously; cannot emit response
*/
> sillence the notice

- js/src/forum/addUploadButton.js
- js/src/forum/components/FileManagerModal.js
This allows the rich text extension to preview links when the markdown driver is selected.
> Insert upload code without escaping

- js/src/forum/components/UserFileList.js
Use Placeholder class for empty UserFileList, that will matches with Flarum
**Screenshot**
Before
After
**Confirmed**
> Use Placeholder class for empty UserFileList

- extend.php
- js/src/admin/components/InspectMimeModal.js
- js/src/admin/components/UploadPage.js
- resources/locale/en.yml
- src/Api/Controllers/InspectMimeController.php
Add a new utility to the admin panel where files can be dropped to see their MIME type and guessed extension.
The feature is mostly standalone. It re-uses the file repository but only to copy the file to the temporary folder. The file is never persisted to database or assets folder.
Are the labels explanatory enough? Is the placement of the test button good?
**Screenshot**
Example with common file:
Example with fallback:
Button to access the tool is below MIME configuration:
**Confirmed**
> MIME inspection tool

- migrations/2020_02_06_01_rename_flagrow_permissions.php
- migrations/2020_02_06_02_rename_flagrow_settings.php
**Relates to https://github.com/flarum/framework/pull/3655**
The current migrations assume Flarum is already installed and resolve dependencies that are only available then. This makes it impossible to directly install an instance with the extension. This PR makes sure the database connection provided is the one used to make the needed changes without resolving anything else.
**Confirmed**
> fix: migrations assume flarum is already installed

- extend.php
- js/src/forum/handler/Uploader.js
- resources/locale/en.yml
- src/Api/Controllers/UploadController.php
- src/Exceptions/ExceptionHandler.php
- src/Exceptions/InvalidUploadException.php
- src/Repositories/FileRepository.php
**Fixes #141**
Handles the `InvalidUploadException` for end user consumption rather than a non-understandable 500.
**Confirmed**
> fix: descriptive upload error messages

- src/Adapters/Manager.php
In cases where AWS configuration is done on server/env the S3 driver should still be instantiable.
Update src/Adapters/Manager.php to not return null when the DB S3 key is not set. This is because the aws-sdk falls back on $_ENV and system configuration (~/.aws/config) for initialization for added security.
It appears this method was already set up to do so, but was later updated to return early.
**Screenshot**
n/a
**Confirmed**
> DB S3 key should not be forced

- js/src/forum/addUploadButton.js
Modify the drag and drop implementation so that Flarum doesn't crash when trying to use `TextEditor` outside of the Composer.
Also make the drag and drop target customizable by extensions so that other extensions can make it work in their custom TextEditor locations.
Example implementation that would use the new function https://github.com/clarkwinkelmann/flarum-ext-composer-page/pull/1
Should be 100% backward-compatible since it only adds new method and none of the code was previously extendable.
**Screenshot**
No visual changes.
**Confirmed**
> Allow TextEditor to be used in non-Composer contexts

- resources/locale/en.yml
- src/Data/Uploads.php
Requires `blomstra/gdpr` `0.1.0-beta.18` or higher in order to enable the support
> feat: add translations, support file deletion via gdpr

- extend.php
- src/Extenders/AddForumAttributes.php
- src/Extenders/AddUserAttributes.php
- src/Extenders/LoadFilesRelationship.php
> perf: eager load file counts

- src/Extenders/LoadFilesRelationship.php
Plucking seems to include null values as well, so we need to filter the collection.
**Confirmed**
> fix: collection might contain null values when eager loading

- src/Commands/UploadHandler.php
The $this->mimeDetector returns an empty array when it does not match any file type. To actually fallback to finfo we have to check if the mime key is not present.
To reproduce, upload a simple txt file and observe an exception when the non existing mime key is accessed.
> Fix fallback mime detection

- extend.php
- js/src/admin/components/UploadPage.js
- src/Helpers/Util.php
- src/Providers/DownloadProvider.php
- src/Providers/UtilProvider.php
- tests/integration/api/FileUploadTest.php
- tests/integration/api/ForumAttributesTest.php
For some reason, with the last changes none of the translations load when the extension is enabled...
> fix: missing translations

- js/src/forum/handler/Uploader.js
This PR fixes the insertion of BBCode after pasting image from clipboard.
After update to v1.5.0 it stopped working.
**Screenshot**
https://github.com/FriendsOfFlarum/upload/assets/25438601/51a2158f-167e-4104-9d3b-323acc3df1dd
**Confirmed**
> fix: insert BBCode on paste

- js/src/common/components/DisplayFile.tsx
- resources/locale/en.yml
- Use translation instead of hardcoded text in the delete file confirmation
- Prevent selecting file on delete 
**Confirmed**
> Fix: delete file button confirmation message and prevent selecting file on delete

- js/src/forum/addUserPageButton.js
Summary:
- Use slug instead of username to ensure compatibility no matter if the slug driver is left to default or id.
> fix(routing): use slug for routing on UserPage

- .github/workflows/issue_stale.yml
Implement a GitHub Actions Workflow for marking issues as stale after 60 days of inactivity and closing them after an additional 30 days. You can review the documentation at https://github.com/actions/stale.
Only issues which are marked with the label "bug" will be processed in the workflow. If issues shall not be closed even when they are marked with "bug", an additional label can be added (for example "keep"), which in turn will exempt the issue from being marked as stale or closed (see `exempt-issue-labels`).
Review if the wording of the workflow itself and the message after an issue has been closed is appropriate.
> ci: implement stale issue handler workflow

- README.md
require accept multiple packages as arguments, using a space will tell composer to install both fof/upload and "*". Using the : delimiter will help it understand the wildcard as version constraint.
https://getcomposer.org/doc/03-cli.md#require-r
**Confirmed**
> fix: readme implies wrong composer require command

- src/Downloader/DefaultDownloader.php
Adding a field of "filename*" for the response header "Content-Disposition" to fix such problem.
> fix: filename is unreadable text when downloading a file with a non-ascii name

- src/Formatter/TextPreview/FormatTextPreview.php
Fixes the "expand" button's misbehavior while using Text Preview.
**Confirmed**
> Fix Condition when Text Preview should be shown

- resources/less/common/fileList.less
Fix UI issue with tooltips of uploaded files (both in the Forum & Admin Frontend)
**Screenshot**
Before:
After:
**Confirmed**
> fix: change UI in tooltips of uploaded files

- js/src/common/components/AbstractFIleList.tsx
- js/src/common/states/FileListState.ts
- resources/less/common/fileList.less
**Fixes https://github.com/FriendsOfFlarum/upload/issues/395**
- Add load more button below file grid
- Append new results when loading more to existing files
**Screenshot**
**Confirmed**
> fix: append new results when loading more to existing files

- .github/workflows/backend.yml
- extend.php
- resources/templates/image-preview.blade.php
- src/Adapters/AwsS3.php
- src/Adapters/Flysystem.php
- src/Adapters/Local.php
- src/Adapters/Manager.php
- src/Adapters/Qiniu.php
- src/Extenders/AddPostDownloadTags.php
- src/File.php
- src/Formatter/ImagePreview/FormatImagePreview.php
- src/Repositories/FileRepository.php
- src/Templates/ImagePreviewTemplate.php
The general purpose of this is to move away from having a single CDN prefix defined in the extension settings, thus allowing multiple adapters to have different hosts.
Also, the storing of the absolute url IMO is bad practice, and this should be generated based on the specific adapter settings.
We cannot clean all of this up without a major breaking change, so this PR starts the process by allowing either the old url or the new uuid parameters.
> feat: begin to move away from hard coded base urls

- js/src/admin/components/UploadPage.js
Default Mime Types in the Admin UI still shows `^image\/.*` instead of `^image\/(jpeg|png|gif|webp|avif|bmp|tiff|svg\+xml)$`. See #429 
**Screenshot**
**Confirmed**
> fix: change mimetype default in admin UI

- src/Adapters/Flysystem.php
Set a default value to $contents to prevent getting warning "PHP Deprecated:  Optional parameter $upload declared before required parameter $contents is implicitly treated as a required parameter"
Fixes #422
> fix: resolve deprecation warning
